Add lockfile check to Husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,17 @@
 #!/bin/sh
+
 set -e
+
+SYMBOL_PASS="\xE2\x9C\x94"
+SYMBOL_FAIL="\xE2\x9D\x8C"
 
 yarn lint-staged
 yarn nx workspace-lint
+
+echo "Verifying lockfile..."
+if ! yarn install --frozen-lockfile > /dev/null; then
+    echo "$SYMBOL_FAIL package.json does not correspond to yarn.lock"
+    exit 1
+else
+    echo "$SYMBOL_PASS Lockfile verified"
+fi
